### PR TITLE
Running JUnit tests on both browsers

### PR DESCRIPTION
**Pull request by elgreco247**
Here's a suggestion for running the JUnit tests on both browsers. I have implemented it only for the Java tests. What do you think?

### CODE REVIEW

**Comment by lsoares** [comment]
It's a good idea, but wouldn't you prefer running everything in both? like two separate phases in CI/CD (each with a different env var that the driver creation would read from)? each run only takes 2 minutes.. locally you'd run only one of them anyway... and then you wouln't have to put these annotations everywhere.

I agree with the part about img/input.. although a parameterized test would suffice.
However, as the project is mostly Kotlin I'd do it in Kotlin. the coverage is all there.
That Java test is only for experiment how the Java tailored API feels like.

**Comment by elgreco247** [comment]
Agreed. I'll close the PR.

**Comment by lsoares** [comment]
[check this](https://github.com/lsoares/selenium-testing-library/commit/05f774d0f7d113bc13070395eff2f6a7c021e992)

**Comment by elgreco247** [comment]
Maybe for now we should add `--tests "seleniumtestinglib.locators.*"` to the Firefox tests (see also https://github.com/lsoares/selenium-testing-library/issues/7#issuecomment-1976522075)

**Comment by lsoares** [comment]
yes, let's do that. I'm still not sure if it's worth maitaining the user-event or not but since I'm not using the project in real-life right now, it's hard to make a call without feedback.

**Pull request closed without merging**
